using APIGateWay.ModalLayer.Helper;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static APIGateWay.ModalLayer.Helper.PostHelper;

namespace APIGateWay.ModalLayer.MasterData
    {
        public class ProjectMaster : IAuditableEntity, IAuditableUser
        {
        // --------------------------------------------------------
        // 🔴 IGNORED FIELDS (Server Generated)
        // --------------------------------------------------------
        [Key]
        [IgnoreMapping] // Generated manually via Guid.NewGuid() in Business Layer
        public Guid? Id { get; set; }
        [IgnoreMapping] // Generated by GetNextSequenceAsync
            public int SiNo { get; set; }

            [IgnoreMapping] // Generated by GetNextSequenceAsync
            public string ProjectKey { get; set; }


            [IgnoreMapping] // Hardcoded to 1 (
                            // ) in Business Layer
            public int? Status { get; set; }

            [IgnoreMapping] // Handled strictly by HtmlUtilities.ConvertToPlainText()
            public string Description { get; set; }

            [IgnoreMapping] // Handled strictly by ProcessAndCopyAttachmentsAsync()
            public string? HtmlDesc { get; set; }

            // --------------------------------------------------------
            // 🟢 MAPPED FIELDS (Coming straight from DTO / UI)
            // --------------------------------------------------------

            public string Title { get; set; }
            public string? RepoKey { get; set; }
            public Guid? Responsible { get; set; }
            public DateTime? StartDate { get; set; }
            public DateTime? DueDate { get; set; }
            public Guid? Repo_Id { get; set; }

            // --------------------------------------------------------
            // 🛡️ AUDIT FIELDS (Handled dynamically)
            // --------------------------------------------------------
            // 💡 Notice: No [IgnoreMapping] is needed here! 
            // Because your class uses IAuditableEntity & IAuditableUser, 
            // our dynamic AutoMapper extension automatically ignores these 4 fields!

            public DateTime? CreatedAt { get; set; }
            public Guid? CreatedBy { get; set; }
            public DateTime? UpdatedAt { get; set; }
            public Guid? UpdatedBy { get; set; }
        }
    }

