using APIGateWay.ModalLayer.Helper;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static APIGateWay.ModalLayer.Helper.PostHelper;

namespace APIGateWay.ModalLayer.MasterData
{
    public class ThreadMaster : IAuditableEntity, IAuditableUser
    {
        [Key]
        [IgnoreMapping] // Generated by GetNextSequenceAsync
        public long ThreadId { get; set; }
        public int? FailedHandoffId { get; set; }

        [IgnoreMapping]
        public string? RepoKey { get; set; }
        [IgnoreMapping]
        public string? IssueTitle { get; set; }


        public Guid Issue_Id { get; set; }

        [IgnoreMapping] // Handled strictly by ProcessAndCopyAttachmentsAsync()
        public string? HtmlDesc { get; set; }
        public string? CommentText { get; set; }
        public string? Ref_Id { get; set; }
        public string? ThreadType { get; set; }
        public Guid? MeetingId { get; set; }
        public string? Hours { get; set; }
        public decimal? CompletionPct { get; set; }
        public DateTime? From_Time { get; set; }
        public DateTime? To_Time { get; set; }
        public int? HandsOffId { get; set; }
        public bool? toClient { get; set; }

        // --------------------------------------------------------
        // 🛡️ AUDIT FIELDS (Handled dynamically)
        // --------------------------------------------------------
        // 💡 Notice: No [IgnoreMapping] is needed here! 
        // Because your class uses IAuditableEntity & IAuditableUser, 
        // our dynamic AutoMapper extension automatically ignores these 4 fields!
        public Guid? WorkStreamId { get; set; }
        public DateTime? CreatedAt { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public Guid? UpdatedBy { get; set; }

        [ForeignKey("FailedHandoffId")]
        public virtual WorkStreamHandoff FailedHandoff { get; set; }
    }
}
