using APIGateWay.ModalLayer.Helper;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static APIGateWay.ModalLayer.Helper.PostHelper;

namespace APIGateWay.ModalLayer.MasterData
{
    public class TicketMaster : IAuditableEntity, IAuditableUser
    {
        [Key]
        [IgnoreMapping] // Generated manually via Guid.NewGuid() in Business Layer
        public Guid? Issue_Id { get; set; }
        [IgnoreMapping] // Generated by GetNextSequenceAsync
        public int SiNo { get; set; }

        [IgnoreMapping] // Generated by GetNextSequenceAsync
        public string Issue_Code { get; set; }
        [IgnoreMapping] // Generated by GetNextSequenceAsync
        public string? RepoKey { get; set; }
        public string? ProjKey { get; set; }

        public int? Status { get; set; }

        [IgnoreMapping] // Handled strictly by HtmlUtilities.ConvertToPlainText()
        public string Description { get; set; }

        [IgnoreMapping] // Handled strictly by ProcessAndCopyAttachmentsAsync()
        public string? HtmlDesc { get; set; }

        public string Title { get; set; }
        //public string RepoKey { get; set; }
        public string? Hours { get; set; }
        public string? Priority { get; set; }
        public string? StatusName { get; set; }
        public decimal? CompletionPct { get; set; }
        public decimal? OverallPercentage { get; set; }
        public bool IsCloseRequested { get; set; }
        //public string? StreamName { get; set; }
        public int? ReopenCount { get; set; }
        public Guid? ReopenedBy { get; set; }
        public Guid? Assignee_Id { get; set; }
        public Guid? Project_Id { get; set; }
        public DateTime? Due_Date { get; set; }
        public Guid? RepoId { get; set; }
        public bool PriorityRequest { get; set; }
        public bool FuncResponse { get; set; }
        public bool WebResponse { get; set; }
        public bool TechnicalResponse { get; set; }
        public bool AdminResponse { get; set; }
        public bool RaiseToClient { get; set; }
        //public Guid? StreamId { get; set; }
        //public Guid? ResourceId { get; set; }

        // --------------------------------------------------------
        // 🛡️ AUDIT FIELDS (Handled dynamically)
        // --------------------------------------------------------
        // 💡 Notice: No [IgnoreMapping] is needed here! 
        // Because your class uses IAuditableEntity & IAuditableUser, 
        // our dynamic AutoMapper extension automatically ignores these 4 fields!

        public DateTime? CreatedAt { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public Guid? UpdatedBy { get; set; }
        public string? Technical { get; set; }
        public string? Functional { get; set; }
        public string? Web { get; set; }
        public string? Client { get; set; }

    }
}
